export const ADMIN_AUDIT_ACTIONS = [
  "STUDENT_CREATED",
  "STUDENT_UPDATED",
  "STUDENT_STATUS_CHANGED",
  "PARENT_CREATED",
  "PARENT_UPDATED",
  "PARENT_LINKED",
  "PARENT_UNLINKED",
  "COACH_CREATED",
  "COACH_UPDATED",
  "BATCH_CREATED",
  "BATCH_UPDATED",
  "BATCH_COACH_ASSIGNED",
  "BATCH_COACH_UNASSIGNED",
  "SCHEDULE_CREATED",
  "SCHEDULE_UPDATED",
  "ENROLLMENT_CREATED",
  "ENROLLMENT_UPDATED",
  "BATCH_ENROLLMENT_CREATED",
  "BATCH_ENROLLMENT_ENDED",
  "ACCOUNT_INVITED",
  "ACCOUNT_CREATED",
  "ACCOUNT_DEACTIVATED",
  "ACCOUNT_REACTIVATED",
  "ROLE_CHANGED",
  "BULK_IMPORT_COMPLETED",
] as const;

/** Mirrors the `admin_audit_log_entity_type_check` constraint in supabase/migrations/0014_admin_audit_and_functions.sql. */
export const ADMIN_AUDIT_ENTITY_TYPES = [
  "student",
  "parent",
  "coach",
  "batch",
  "schedule",
  "enrollment",
  "batch_enrollment",
  "account",
  "role",
  "import",
] as const;
